services:
    putio.drive.controller:
        class: Gpenverne\\PutioDriveBundle\\Controller\\PutioController
        arguments:
            - "@dispatcher"
            - "@putio.drive.http_client"
            - "@request_stack"
            - "@putio.drive.url_generator"
    putio.drive.http_client:
        class: Gpenverne\\PutioDriveBundle\\Service\\HttpClient
    putio.drive.url_generator:
        class: Gpenverne\\PutioDriveBundle\\Service\\UrlGenerator
        parameters:
            - "%putio%"
