putio:
    callback:
        path:     /putio/callback
        defaults: { _controller: putio.drive.controller:callbackAction }
    redirect:
        path:     /putio/redirect
        defaults: { _controller: putio.drive.controller:redirectAction }
