services:
    # --- controller
    putio.drive.controller:
        class: Gpenverne\PutioDriveBundle\Controller\PutioController
        arguments:
            - "@putio.drive.url_generator"
            - "@putio.drive"

    # -- factory
    putio.drive:
        class: Gpenverne\PutioDriveBundle\Factory\PutioApiFactory
        arguments:
            - "@psr_cloud_files.factory.folder"
            - "@psr_cloud_files.factory.file"

    # -- utils
    putio.drive.http_client:
        class: Gpenverne\PutioDriveBundle\Service\HttpClient
    putio.drive.url_generator:
        class: Gpenverne\PutioDriveBundle\Service\UrlGenerator
        arguments:
            - "@router"
            - "%putio%"

    # --- listeners
    putio.drive.listener.code:
        class: Gpenverne\PutioDriveBundle\EventListener\PutioCodeEventListener
        arguments:
            - "@putio.drive"
        tags:
            - { name: kernel.event_listener, event: events.putio.code, method: onCodeObtained, priority: 0 }
    putio.drive.listener.token:
        class: Gpenverne\PutioDriveBundle\EventListener\PutioTokenEventListener
        arguments:
            - "@putio.drive"
        tags:
            - { name: kernel.event_listener, event: events.putio.token, method: onTokenObtained, priority: 0 }

    # --- subscribers
    putio.drive.endpoint_listener:
        class: Gpenverne\PutioDriveBundle\EventListener\PutioEndPointSubscriber
        arguments:
            - "@event_dispatcher"
            - "%putio.callback_route%"
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 0 }


    # -- external
    psr_cloud_files.factory.folder:
        class: Gpenverne\PsrCloudFiles\Factory\FolderFactory
    psr_cloud_files.factory.file:
        class: Gpenverne\PsrCloudFiles\Factory\FileFactory
